<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFrameworks>net11.0;net11.0-android;net11.0-ios;net11.0-maccatalyst;net11.0-macos;net11.0-browser</TargetFrameworks>
    <TargetFrameworks>$(TargetFrameworks);net11.0-windows10.0.19041.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>Avae.Notifications</PackageId>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <!--<TreatWarningsAsErrors>true</TreatWarningsAsErrors>-->
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\**" />
    <None Include="wwwroot\blazor-notifications.js" />
    <TfmSpecificPackageFile Include="wwwroot\**">
      <PackagePath>lib\$(TargetFramework)\wwwroot\%(RecursiveDir)%(Filename)%(Extension)</PackagePath>
      <PackageCopyToOutput>true</PackageCopyToOutput>
    </TfmSpecificPackageFile>

    <Compile Remove="Blazor\**" />
    <TfmSpecificPackageFile Include="Blazor\**">
      <PackagePath>lib\$(TargetFramework)\Blazor\%(RecursiveDir)%(Filename)%(Extension)</PackagePath>
      <PackageCopyToOutput>true</PackageCopyToOutput>
    </TfmSpecificPackageFile>

    <Compile Remove="Maui\**" />
    <TfmSpecificPackageFile Include="Maui\**">
      <PackagePath>lib\$(TargetFramework)\Maui\%(RecursiveDir)%(Filename)%(Extension)</PackagePath>
      <PackageCopyToOutput>true</PackageCopyToOutput>
    </TfmSpecificPackageFile>
  </ItemGroup>

  <ItemGroup>
    <Content Include="build\**" PackagePath="buildtransitive\" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Avae.Services\Avae.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Labs.Notifications" />
  </ItemGroup>

</Project>