<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net11.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!--<LangVersion>preview</LangVersion>-->
    <!--<TreatWarningsAsErrors>true</TreatWarningsAsErrors>-->
    <AvaeFeatures>;CommunityToolkit;</AvaeFeatures>
  </PropertyGroup>

  <PropertyGroup>
    <_KernelRelease Condition="Exists('/proc/sys/kernel/osrelease')">$([System.IO.File]::ReadAllText('/proc/sys/kernel/osrelease').ToLowerInvariant())</_KernelRelease>
    <IsWslOS Condition="$(_KernelRelease.Contains('microsoft')) OR $(_KernelRelease.Contains('wsl')) OR '$(WSL_DISTRO_NAME)' != '' OR '$(WSL_INTEROP)' != ''">true</IsWslOS>
    <DefineConstants Condition="'$(IsWslOS)' == 'true'">$(DefineConstants);LINUX_OS</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avae.Essentials" />
    <PackageReference Include="Avae.Services" />
    <PackageReference Include="Avae.ViewModels" />
    <!--<PackageReference Include="ReactiveUI" />
    <PackageReference Include="ReactiveUI.SourceGenerators">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>-->
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Example.Models\Example.Models.csproj" />
  </ItemGroup>

</Project>
