<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net11.0-browser</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <!-- Following are required to redirect like  Use(async (ctx, next) in Blazor server to use scope while registering service worker -->
    <!-- Microsoft.AspNetCore.Components.WebAssembly.DevServer must be replace by Toolbelt.Blazor.WebAssembly.ExtensibleDevServer -->
    <!--<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.9" PrivateAssets="all" />-->
    <PackageReference Include="BlazorWebAssemblyExtension">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Toolbelt.Blazor.WebAssembly.ExtensibleDevServer" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />    
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Bases\Avae.Avalonia.Essentials\Avae.Avalonia.Essentials.csproj" />
    <ProjectReference Include="..\..\Bases\Avae.Blazor.Notifications\Avae.Blazor.Notifications.csproj" />
    <ProjectReference Include="..\..\Bases\Avae.ViewModels\Avae.ViewModels.csproj" />
    <ProjectReference Include="..\..\Bases\Avae.Avalonia.Browser\Avae.Avalonia.Browser.csproj" />
    <ProjectReference Include="..\Example.Razor\Example.Razor.csproj" />
  </ItemGroup>

</Project>
