<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net11.0-browser</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AvaeFeatures>;Embedded;</AvaeFeatures>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avae.Notifications" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all" />    
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Bases\Avae.ViewModels\Avae.ViewModels.csproj" />
    <ProjectReference Include="..\Example.Razor\Example.Razor.csproj" />
  </ItemGroup>

</Project>
