<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>    
    <PackageReference Update="Avalonia" />
    <PackageReference Include="FluentAvaloniaUI" />
    <PackageReference Include="MessageBox.Avalonia" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Avae.Services\Avae.Services.csproj" />
    <ProjectReference Include="..\Avae.ViewModels\Avae.ViewModels.csproj" />
  </ItemGroup>

</Project>
