<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="MessageBox.Avalonia" />
    <PackageReference Include="FluentAvaloniaUI" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Avae.Services\Avae.Services.csproj" />
    <ProjectReference Include="..\Avae.ViewModels\Avae.ViewModels.csproj" />
  </ItemGroup>

</Project>
