<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <AvaloniaVersion>12.1.2</AvaloniaVersion>
    <MauiVersion>11.0.0-rc.1.26451.6</MauiVersion>
    <MicrosoftVersion>10.0.11</MicrosoftVersion>
    <MagicOnionVersion>7.10.2</MagicOnionVersion>
    <GrpcVersion>2.83.0</GrpcVersion>
    <GrpcBridgeVersion>1.4.1</GrpcBridgeVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Avae.Avalonia" Version="1.0.0-preview.1" />
    <PackageVersion Include="Avae.EmbeddedApp" Version="1.0.0-preview.1" />
    <PackageVersion Include="Avae.DAL" Version="1.0.0-preview.1" />
    <PackageVersion Include="Avae.Essentials" Version="1.0.0-preview.1" />
    <PackageVersion Include="Avae.Notifications" Version="1.0.0-preview.1" />
    <PackageVersion Include="Avae.Services" Version="1.0.0-preview.1" />
    <PackageVersion Include="Avae.ViewModels" Version="1.0.0-preview.1" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageVersion Include="CommunityToolkit.Maui" Version="15.0.1" />
    <!-- AVALONIA -->
    <PackageVersion Include="AathifMahir.Maui.MauiIcons.FontAwesome.Solid" Version="6.0.0" />
    <PackageVersion Include="Avalonia" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Android" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Browser" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Win32" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.iOS" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Skia" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Native" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.HarfBuzz" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Dapper.Contrib" Version="2.0.78" />
    <PackageVersion Include="Dommel" Version="3.5.3" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="$(MicrosoftVersion)" />
    <!--<PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="$(MicrosoftVersion)" />-->
    <PackageVersion Include="Microsoft.JSInterop" Version="11.0.0-rc.1.26425.128" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.Web" Version="$(MicrosoftVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly" Version="$(MicrosoftVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="$(MicrosoftVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="$(MicrosoftVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.SignalR.Client" Version="$(MicrosoftVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" Version="$(MicrosoftVersion)" />
    <PackageVersion Include="Microsoft.Maui.Essentials" Version="11.0.0-rc.1.26451.6" />
    <PackageVersion Include="Optris.Icons.Avalonia.FontAwesome" Version="12.0.7" />
    <PackageVersion Include="ReactiveUI" Version="24.3.0" />
    <PackageVersion Include="ReactiveUI.Avalonia" Version="12.1.2" />
    <PackageVersion Include="ReactiveUI.SourceGenerators" Version="3.2.0" />
    <PackageVersion Include="Splat.Microsoft.Extensions.DependencyInjection" Version="21.0.0" />
    <PackageVersion Include="System.Text.Json" Version="11.0.0-rc.1.26425.128" />
    <PackageVersion Include="Microsoft.Maui.Controls" Version="11.0.0-rc.1.26451.6" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebView.Maui" Version="10.0.100" />
    <PackageVersion Include="WindowsContracts.Net.Foundation.UniversalApiContract" Version="5.19041.10" PrivateAssets="compile" />
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="2.5.1" />
    <PackageVersion Include="Microsoft.Maui.Platforms.MacOS.Essentials" Version="0.1.0-preview.12.26368.2" />
    <PackageVersion Include="Microsoft.Maui.Platforms.Linux.Gtk4.Essentials" Version="0.1.0-preview.12.26421.1" />
    <PackageVersion Include="MudBlazor" Version="9.9.0" />
    <PackageVersion Include="Append.Blazor.WebShare" Version="7.0.0" />
    <PackageVersion Include="BlazorNative.Device" Version="0.12.0" />
    <PackageVersion Include="BlazorSensors" Version="1.0.1" />
    <PackageVersion Include="KristofferStrube.Blazor.FileSystemAccess" Version="4.0.0" />
    <PackageVersion Include="KristofferStrube.Blazor.MediaCaptureStreams" Version="0.4.1" />
    <PackageVersion Include="KristofferStrube.Blazor.MediaStreamRecording" Version="0.1.0-alpha.2" />
    <PackageVersion Include="PatrickJahr.Blazor.AsyncClipboard" Version="1.0.0" />
    <PackageVersion Include="Toolbelt.Blazor.SpeechSynthesis" Version="11.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.SignalR.Core" Version="1.2.12" />
    <PackageVersion Include="MagicOnion.Serialization.MessagePack" Version="$(MagicOnionVersion)" />
    <PackageVersion Include="MagicOnion.Abstractions" Version="7.11.0" />
    <PackageVersion Include="MagicOnion.Client" Version="$(MagicOnionVersion)" />
    <PackageVersion Include="MagicOnion.Server" Version="$(MagicOnionVersion)" />
    <PackageVersion Include="Grpc.AspNetCore.Web" Version="$(GrpcVersion)" />
    <PackageVersion Include="Grpc.AspNetCore" Version="$(GrpcVersion)" />
    <PackageVersion Include="Grpc.Net.Client.Web" Version="$(GrpcVersion)" />
    <PackageVersion Include="GrpcWebSocketBridge.Client" Version="$(GrpcBridgeVersion)" />
    <PackageVersion Include="GrpcWebSocketBridge.AspNetCore" Version="$(GrpcBridgeVersion)" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageVersion Include="SqlTableDependencyCore" Version="1.0.0" />
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="11.0.0-preview.6.26359.118" />
  </ItemGroup>
</Project>