<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <AvaloniaVersion>12.1.1</AvaloniaVersion>
    <MauiVersion>11.0.0-preview.6.26360.8</MauiVersion>    
    <MicrosoftVersion>10.0.11</MicrosoftVersion>
    <MagicOnionVersion>7.10.2</MagicOnionVersion>
    <GrpcVersion>2.83.0</GrpcVersion>
    <GrpcBridgeVersion>1.4.1</GrpcBridgeVersion>
  </PropertyGroup>
  <ItemGroup>
    <!-- AVALONIA -->
    <PackageVersion Include="Avalonia" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Android" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Browser" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Win32" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.iOS" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Skia" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Native" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.HarfBuzz" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Labs.Notifications" Version="12.0.999" />
    <PackageVersion Include="Avalonia.Controls.Maui.Essentials" Version="11.0.0-preview.5.26161.128" />
    <PackageVersion Include="MessageBox.Avalonia" Version="12.0.0" />
    <PackageVersion Include="FluentAvaloniaUI" Version="3.1.0" />
    <!-- DEPENDENCY INJECTION -->
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="$(MicrosoftVersion)" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="$(MicrosoftVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="$(MicrosoftVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="$(MicrosoftVersion)" />
    <PackageVersion Include="Microsoft.JSInterop" Version="$(MicrosoftVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.Web" Version="$(MicrosoftVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly" Version="$(MicrosoftVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="$(MicrosoftVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="$(MicrosoftVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.SignalR.Client" Version="$(MicrosoftVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" Version="$(MicrosoftVersion)" />
    
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageVersion Include="System.Text.Json" Version="11.0.0-preview.7.26381.103" />
    <!-- MAUI -->
    <PackageVersion Include="UXDivers.Popups.Maui" Version="0.9.4" />
    <PackageVersion Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebView.Maui" Version="10.0.100" />
    <!-- ESSENTIALS -->
    <PackageVersion Include="Microsoft.Maui.Essentials" Version="$(MauiVersion)" />
    <PackageVersion Include="WindowsContracts.Net.Foundation.UniversalApiContract" Version="5.19041.10" PrivateAssets="compile" />
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="1.8.251106002" />
    <PackageVersion Include="Microsoft.Maui.Platforms.MacOS.Essentials" Version="0.1.0-preview.12.26368.2" />
    <PackageVersion Include="Microsoft.Maui.Platforms.Linux.Gtk4.Essentials" Version="0.1.0-preview.12.26421.1" />
    <!-- BLAZOR -->
    <PackageVersion Include="MudBlazor" Version="9.9.0" />
    <!-- BLAZOR ESSENTIALS -->
    <PackageVersion Include="Append.Blazor.WebShare" Version="7.0.0" />
    <PackageVersion Include="BlazorNative.Device" Version="0.12.0" />
    <PackageVersion Include="BlazorSensors" Version="1.0.1" />
    <PackageVersion Include="KristofferStrube.Blazor.FileSystemAccess" Version="4.0.0" />
    <PackageVersion Include="KristofferStrube.Blazor.MediaCaptureStreams" Version="0.4.1" />
    <PackageVersion Include="KristofferStrube.Blazor.MediaStreamRecording" Version="0.1.0-alpha.2" />    
    <PackageVersion Include="PatrickJahr.Blazor.AsyncClipboard" Version="1.0.0" />
    <PackageVersion Include="Toolbelt.Blazor.SpeechSynthesis" Version="11.0.0" />
    <!-- WASM -->
    
    <!-- SIGNAL R-->
    <PackageVersion Include="Microsoft.AspNetCore.SignalR.Core" Version="1.2.12" />    
    <!-- Grpc -->
    <PackageVersion Include="MessagePack" Version="3.1.8" />
    <PackageVersion Include="MagicOnion.Serialization.MessagePack" Version="$(MagicOnionVersion)" />
    <PackageVersion Include="MagicOnion.Abstractions" Version="$(MagicOnionVersion)" />
    <PackageVersion Include="MagicOnion.Client" Version="$(MagicOnionVersion)" />
    <PackageVersion Include="MagicOnion.Server" Version="$(MagicOnionVersion)" />
    <PackageVersion Include="Grpc.AspNetCore.Web" Version="$(GrpcVersion)" />
    <PackageVersion Include="Grpc.AspNetCore" Version="$(GrpcVersion)" />    
    <PackageVersion Include="Grpc.Net.Client.Web" Version="$(GrpcVersion)" />
    <PackageVersion Include="GrpcWebSocketBridge.Client" Version="$(GrpcBridgeVersion)" />
    <PackageVersion Include="GrpcWebSocketBridge.AspNetCore" Version="$(GrpcBridgeVersion)" />    
    <!-- LAYERS -->
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageVersion Include="SqlTableDependencyCore" Version="1.0.0" />
    <PackageVersion Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="11.0.0-preview.6.26359.118" />
    <PackageVersion Include="Dapper.Contrib" Version="2.0.78" />
    <!-- LOGS -->
    <PackageVersion Include="System.Diagnostics.EventLog" Version="$(MicrosoftVersion)" />
    <!-- TESTS -->
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageVersion Include="NSubstitute" Version="6.2.0" />
    <PackageVersion Include="xunit.v3" Version="4.0.0" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="4.0.0" />
  </ItemGroup>
</Project>