<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <!--<TreatWarningsAsErrors>true</TreatWarningsAsErrors>-->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="11.0.0-preview.6.26359.118" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Bases\Avae.Abstractions.Core\Avae.Abstractions.Core.csproj" />
    <ProjectReference Include="..\..\Bases\Avae.Essentials.Avalonia\Avae.Essentials.Avalonia.csproj" />
    <ProjectReference Include="..\..\Bases\Avae.Razor\Avae.Razor.csproj" />
    <ProjectReference Include="..\Example.Razor\Example.Razor.csproj" />
  </ItemGroup>

</Project>
