using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Avae.Generator
{
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
    public class GenerateGoToAttribute : Attribute
    {
        // Optional: Customize overload prefix (default: "GoTo")
        public string MethodName { get; set; } = "GoTo";
    }

    [Generator]
    public class RouterGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Collect all class declarations
            var classDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => node is ClassDeclarationSyntax,
                    transform: static (ctx, _) => (ClassDeclarationSyntax)ctx.Node
                )
                .Where(static c => c is not null);

            // Combine compilation and class declarations
            var combined = context.CompilationProvider.Combine(classDeclarations.Collect());

            context.RegisterSourceOutput(combined, static (spc, source) =>
            {
                var (compilation, classes) = source;
                var viewModelBaseSymbol = compilation.GetTypeByMetadataName("Avae.Abstractions.IViewModelBase");

                if (viewModelBaseSymbol is null)
                    return;

                var viewModels = new List<INamedTypeSymbol>();

                foreach (var classDecl in classes)
                {
                    var model = compilation.GetSemanticModel(classDecl.SyntaxTree);
                    if (model.GetDeclaredSymbol(classDecl) is INamedTypeSymbol typeSymbol &&
                        typeSymbol.AllInterfaces.Contains(viewModelBaseSymbol))
                    {
                        viewModels.Add(typeSymbol);
                    }
                }

                if (viewModels.Count == 0)
                    return;

                var sourceCode = GenerateRouterSource(viewModels);
                spc.AddSource("Router.GoTo.g.cs", sourceCode);
            });
        }

        private static string GenerateRouterSource(IEnumerable<INamedTypeSymbol> viewModels)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System;");
            sb.AppendLine("using Avae.Abstractions;");
            sb.AppendLine("namespace Example.ViewModels");
            sb.AppendLine("{");
            sb.AppendLine("    public static class RouterExtensions");
            sb.AppendLine("    {");

            foreach (var vm in viewModels)
            {
                string fullName = vm.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                foreach (var ctor in vm.Constructors.Where(c => c.DeclaredAccessibility == Accessibility.Public))
                {
                    var parameters = ctor.Parameters;
                    string paramList = string.Join(", ",
                        parameters.Select(p => $"{p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} {p.Name}"));
                    string argList = string.Join(", ", parameters.Select(p => p.Name));

                    sb.AppendLine($"        public void GoTo<{fullName}>(this Router router, {paramList})");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            var viewModel = new {fullName}({argList});");
                    sb.AppendLine($"            GoTo(viewModel);");
                    sb.AppendLine("        }");
                    sb.AppendLine();
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
