using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Avae.Generator
{
    [Generator]
    public class RouterGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Collect all class declarations
            var classDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => node is ClassDeclarationSyntax,
                    transform: static (ctx, _) => (ClassDeclarationSyntax)ctx.Node
                )
                .Where(static c => c is not null);

            // Combine compilation and class declarations
            var combined = context.CompilationProvider.Combine(classDeclarations.Collect());

            context.RegisterSourceOutput(combined, static (spc, source) =>
            {
                var (compilation, classes) = source;
                var viewModelBaseSymbol = compilation.GetTypeByMetadataName("Avae.Abstractions.IViewModelBase");

                if (viewModelBaseSymbol is null)
                    return;

                var viewModels = new List<INamedTypeSymbol>();

                foreach (var classDecl in classes)
                {
                    var model = compilation.GetSemanticModel(classDecl.SyntaxTree);
                    if (model.GetDeclaredSymbol(classDecl) is INamedTypeSymbol typeSymbol &&
                        typeSymbol.AllInterfaces.Contains(viewModelBaseSymbol))
                    {
                        //foreach (var attribute in typeSymbol.GetAttributes())
                        //{
                        //    if (attribute.AttributeClass?.ToDisplayString() == "GoToAttribute")
                        //    {
                                viewModels.Add(typeSymbol);
                        //    }
                        //}
                    }
                }

                if (viewModels.Count == 0)
                    return;

                var sourceCode = GenerateRouterSource(viewModels);
                spc.AddSource("Router.GoTo.g.cs", sourceCode);
            });
        }

        private static string GenerateRouterSource(IEnumerable<INamedTypeSymbol> viewModels)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System;");
            sb.AppendLine("using Avae.Abstractions;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("namespace Example.ViewModels");
            sb.AppendLine("{");
            sb.AppendLine("    internal static class RouterExtensions");
            sb.AppendLine("    {");

            foreach (var vm in viewModels)
            {
                string fullName = vm.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                foreach (var ctor in vm.Constructors.Where(c => c.DeclaredAccessibility == Accessibility.Public))
                {
                    var parameters = ctor.Parameters;
                    if (parameters.Any())
                    {
                        string paramList = string.Join(", ",
                            parameters.Select(p => $"{p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} {p.Name}"));
                        string argList = string.Join(", ", parameters.Select(p => p.Name));

                        sb.AppendLine($"        public static {vm.Name} GoTo{vm.Name.Replace("ViewModel", string.Empty)}(this Avae.Abstractions.Router abstractRouter, out Avae.Abstractions.IViewModelBase viewModel,  {paramList})");
                        sb.AppendLine("        {");
                        sb.AppendLine($"           var names = new object[] {{ {string.Join(",", parameters.Select(p => p.Name))} }};");
                        sb.AppendLine($"           var parameters = names.Select(name => name.ForViewModel()).ToArray();");
                        sb.AppendLine($"          return abstractRouter.GoTo(typeof({vm.Name}), out viewModel, parameters);");
                        sb.AppendLine("        }");
                        sb.AppendLine();
                    }
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
