<Project Sdk="Uno.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0-android;net10.0-ios;net10.0-browserwasm;net10.0-desktop</TargetFrameworks>

    <OutputType>Exe</OutputType>
    <UnoSingleProject>true</UnoSingleProject>

    <!-- Display name -->
    <ApplicationTitle>Example.Uno</ApplicationTitle>
    <!-- App Identifier -->
    <ApplicationId>com.companyname.Example.Uno</ApplicationId>
    <!-- Versions -->
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <!-- Package Publisher -->
    <ApplicationPublisher>cedri</ApplicationPublisher>
    <!-- Package Description -->
    <Description>Example.Uno powered by Uno Platform.</Description>

    <!--
      UnoFeatures are used to quickly add and manage features enabled for your app.
      https://aka.platform.uno/singleproject-features
    -->
    <UnoFeatures>
      SimpleTheme;
      Hosting;
      Toolkit;
      Logging;
      MauiEmbedding;
      Mvvm;
      Configuration;
      HttpKiota;
      Serialization;
      Localization;
      Navigation;
      ThemeService;
      SkiaRenderer;
    </UnoFeatures>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Example.Uno.MauiControls\Example.Uno.MauiControls.csproj" />
  </ItemGroup>

</Project>
