<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
  </ItemGroup>
  
  <ItemGroup>    
    <ProjectReference Include="..\Avae.Abstractions\Avae.Abstractions.csproj" />
    <ProjectReference Include="..\Avae.Services\Avae.Services.csproj" />    
    <ProjectReference Include="..\Avae.Shared\Avae.EssentialsExtensions.csproj" />
    <ProjectReference Include="..\Example.Models\Example.Models.csproj" />
  </ItemGroup>

</Project>
