<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="ReactiveUI.Avalonia" Version="11.3.0" />
    <PackageReference Include="ReactiveUI.SourceGenerators" Version="2.5.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  
  <ItemGroup>    
    <ProjectReference Include="..\Avae.Abstractions\Avae.Abstractions.csproj" />
    <ProjectReference Include="..\Avae.DAL\Avae.DAL.csproj" />
    <ProjectReference Include="..\Avae.Services\Avae.Services.csproj" />
    <ProjectReference Include="..\Example.Models\Example.Models.csproj" />
  </ItemGroup>

</Project>
