<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net11.0;net11.0-android;net11.0-ios;net11.0-maccatalyst</TargetFrameworks>
    <TargetFrameworks>$(TargetFrameworks);net11.0-windows10.0.19041.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <RootNamespace>Avae.Maui</RootNamespace>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Themes\ErrorStyles.xaml.cs" />
  </ItemGroup>

  <ItemGroup>
    <MauiXaml Remove="Themes\ErrorStyles.xaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="UXDivers.Popups.Maui" />
    <PackageReference Include="Microsoft.Maui.Controls" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Avae.Services\Avae.Services.csproj" />
    <ProjectReference Include="..\Avae.ViewModels\Avae.ViewModels.csproj" />
  </ItemGroup>

  <ItemGroup>
    <MauiXaml Update="AvaePopupPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Themes\" />
  </ItemGroup>

</Project>