<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\avalonia-logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.10" />    
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Bases\Avae.Services\Avae.Services.csproj" />
    <ProjectReference Include="..\..\Bases\Avae.ViewModels\Avae.ViewModels.csproj" />
    <ProjectReference Include="..\..\Bases\Avae.Razor\Avae.Razor.csproj" />
    <ProjectReference Include="..\Example.DAL\Example.DAL.csproj" />
    <ProjectReference Include="..\Example.Models\Example.Models.csproj" />
    <ProjectReference Include="..\Example.ViewModels\Example.ViewModels.csproj" />
  </ItemGroup>
</Project>
