<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AvaeFeatures>;Razor;</AvaeFeatures>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\avalonia-logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avae.Abstractions" />
    <PackageReference Include="Avae.Services" />
    <PackageReference Include="Avae.ViewModels" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Example.DAL\Example.DAL.csproj" />
    <ProjectReference Include="..\Example.Models\Example.Models.csproj" />
    <ProjectReference Include="..\Example.ViewModels\Example.ViewModels.csproj" />
  </ItemGroup>
</Project>
