<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Components\Routes.razor" />
    <Content Remove="Components\_Imports.razor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Example.Razor\Example.Razor.csproj" />
  </ItemGroup>

</Project>
