<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
      <PackageReference Include="Grpc.AspNetCore.Web" />
      <PackageReference Include="Grpc.AspNetCore" />
      <PackageReference Include="MagicOnion.Server" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Avae.DAL.gRPC\Avae.DAL.gRPC.csproj" />
  </ItemGroup>
</Project>
