<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Remove="Assets\Certificates\server.crt" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\Certificates\server.crt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>    
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Bases\Avae.Avalonia.Essentials\Avae.Avalonia.Essentials.csproj" />
    <ProjectReference Include="..\..\Bases\Avae.Avalonia.Notifications\Avae.Avalonia.Notifications.csproj" />
    <ProjectReference Include="..\..\Bases\Avae.ViewModels\Avae.ViewModels.csproj" />
    <ProjectReference Include="..\..\Bases\Avae.Avalonia\Avae.Avalonia.csproj" />
    <ProjectReference Include="..\..\Bases\Avae.DAL\Avae.DAL.csproj" />
    <ProjectReference Include="..\Example.DAL\Example.DAL.csproj" />
    <ProjectReference Include="..\Example.Models\Example.Models.csproj" />
    <ProjectReference Include="..\Example.ViewModels\Example.ViewModels.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Update="Assets\avalonia-logo.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </AvaloniaResource>
  </ItemGroup>
</Project>
