<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <Nullable>enable</Nullable>
    <!--<TreatWarningsAsErrors>true</TreatWarningsAsErrors>-->
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Remove="Assets\Certificates\server.crt" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\Certificates\server.crt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avae.Notifications" />
    <PackageReference Include="Avae.Avalonia" />
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" />
    <PackageReference Include="Optris.Icons.Avalonia.FontAwesome" />
    <PackageReference Include="ReactiveUI.Avalonia" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Example.Models\Example.Models.csproj" />
    <ProjectReference Include="..\Example.ViewModels\Example.ViewModels.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Update="Assets\avalonia-logo.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </AvaloniaResource>
  </ItemGroup>
</Project>
