<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!--<TreatWarningsAsErrors>true</TreatWarningsAsErrors>-->
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="BlazorGeolocation.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Append.Blazor.WebShare" />
    <PackageReference Include="BlazorNative.Device" />
    <PackageReference Include="BlazorSensors" />
    <PackageReference Include="KristofferStrube.Blazor.FileSystemAccess" />
    <PackageReference Include="KristofferStrube.Blazor.MediaCaptureStreams" />
    <PackageReference Include="KristofferStrube.Blazor.MediaStreamRecording" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.JSInterop" />
    <PackageReference Include="Microsoft.Maui.Essentials" />
    <PackageReference Include="PatrickJahr.Blazor.AsyncClipboard" />
    <PackageReference Include="Toolbelt.Blazor.SpeechSynthesis" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Avae.Core\Avae.Core.csproj" />
    <ProjectReference Include="..\Avae.Essentials\Avae.Essentials.csproj" />
  </ItemGroup>
  
</Project>
