<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AvaeFeatures>;MagicServer;</AvaeFeatures>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GrpcWebSocketBridge.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Example.DAL\Example.DAL.csproj" />
    <ProjectReference Include="..\Example.Models\Example.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Certificates\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Certificates\server.crt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Certificates\server.key">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Certificates\server.pfx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
