<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net10.0-android;net10.0-ios;net10.0-macos;</TargetFrameworks>
    <TargetFrameworks>$(TargetFrameworks);net10.0-windows10.0.19041.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Labs.Notifications" Version="12.0.2" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Bases\Avae.Services\Avae.Services.csproj" />
  </ItemGroup>

</Project>
