<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>
  
  
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Avae.Services\Avae.Services.csproj" />
    <ProjectReference Include="..\Avae.ViewModels\Avae.ViewModels.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="buildTransitive\**" PackagePath="buildTransitive\" />
    <Compile Remove="Avalonia\**" />
    <None Remove="Avalonia\**" />
    <Compile Remove="Maui\**" />
    <None Remove="Maui\**" />
    <Compile Remove="Razor\**" />
    <None Remove="Razor\**" />
    <Content Remove="Razor\**" />
    <Compile Remove="Components\**" />
    <None Remove="Components\**" />
    <Content Remove="Components\**" />
    <Compile Remove="Embedded\**" />
    <TfmSpecificPackageFile Include="Avalonia\**">
      <PackagePath>lib\$(TargetFramework)\Avalonia\%(RecursiveDir)%(Filename)%(Extension)</PackagePath>
      <PackageCopyToOutput>true</PackageCopyToOutput>
    </TfmSpecificPackageFile>
    <TfmSpecificPackageFile Include="Maui\**">
      <PackagePath>lib\$(TargetFramework)\Maui\%(RecursiveDir)%(Filename)%(Extension)</PackagePath>
      <PackageCopyToOutput>true</PackageCopyToOutput>
    </TfmSpecificPackageFile>
    <TfmSpecificPackageFile Include="Razor\**">
      <PackagePath>lib\$(TargetFramework)\Razor\%(RecursiveDir)%(Filename)%(Extension)</PackagePath>
      <PackageCopyToOutput>true</PackageCopyToOutput>
    </TfmSpecificPackageFile>
    <TfmSpecificPackageFile Include="Components\**">
      <PackagePath>lib\$(TargetFramework)\Components\%(RecursiveDir)%(Filename)%(Extension)</PackagePath>
      <PackageCopyToOutput>true</PackageCopyToOutput>
    </TfmSpecificPackageFile>
    <TfmSpecificPackageFile Include="Embedded\**">
      <PackagePath>lib\$(TargetFramework)\Embedded\%(RecursiveDir)%(Filename)%(Extension)</PackagePath>
      <PackageCopyToOutput>true</PackageCopyToOutput>
    </TfmSpecificPackageFile>
  </ItemGroup>

 
</Project>
