<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UnoFeatures>postgre;sqlite;sqlTableDependency;signalR;MagicOnion;MagicClient</UnoFeatures>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avae.DAL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Example.Models\Example.Models.csproj" />
  </ItemGroup>

</Project>
