<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  
  <ItemGroup Condition="$(AvaeFeatures.Contains(';Embedded;'))">
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Browser" />
    <Compile Include="$(MSBuildThisFileDirectory)..\lib\net11.0\Embedded\**\*.cs">
      <Visible>false</Visible>
    </Compile>
  </ItemGroup>

  <ItemGroup Condition="$(AvaeFeatures.Contains(';Razor;'))">
    <PackageReference Update="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="MudBlazor" />
    <Compile Include="$(MSBuildThisFileDirectory)..\lib\net11.0\Razor\**\*.cs">
      <Visible>false</Visible>
    </Compile>
    <RazorComponent Include="$(MSBuildThisFileDirectory)..\lib\net11.0\Components\**\*.css">
      <Link>Components\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <TargetPath>Components\%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
      <CssScope></CssScope>
      <Visible>false</Visible>
    </RazorComponent>
    <Content Include="$(MSBuildThisFileDirectory)..\lib\net11.0\Components\**\*.razor">
      <Link>Components\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <Visible>false</Visible>
    </Content>
  </ItemGroup>

  <ItemGroup Condition="$(AvaeFeatures.Contains(';Maui;'))">
    <PackageReference Include="UXDivers.Popups.Maui" />
    <PackageReference Update="Microsoft.Maui.Controls" />
    <Compile Include="$(MSBuildThisFileDirectory)..\lib\net11.0\Maui\**\*.cs">
      <Visible>false</Visible>
    </Compile>
    <MauiXaml Include="$(MSBuildThisFileDirectory)..\lib\net11.0\Maui\**\*.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
  </ItemGroup>

  <ItemGroup Condition="$(AvaeFeatures.Contains(';Avalonia;'))">
    <PackageReference Update="Avalonia" />
    <PackageReference Include="MessageBox.Avalonia" />
    <PackageReference Include="FluentAvaloniaUI" />
    <Compile Include="$(MSBuildThisFileDirectory)..\lib\net11.0\Avalonia\**\*.cs">
      <Visible>false</Visible>
    </Compile>
    <AvaloniaResource Include="$(MSBuildThisFileDirectory)..\lib\net11.0\Avalonia\**\*.axaml">
      <Visible>false</Visible>
    </AvaloniaResource>
  </ItemGroup>


</Project>