using Avae.Abstractions;
using MessagePack;
using MessagePack.Resolvers;
using System.Runtime.CompilerServices;

namespace Example.Models
{
    public static class ModelInitialization
    {
#pragma warning disable CA2255 // L’attribut ’ModuleInitializer’ ne doit pas être utilisé dans les bibliothèques
        [ModuleInitializer]
#pragma warning restore CA2255 // L’attribut ’ModuleInitializer’ ne doit pas être utilisé dans les bibliothèques
        public static void Init()
        {
            InputValidation<Person>.Init();

    //        StaticCompositeResolver.Instance.Register(
    //    // Use the resolver generated by the source generator
    //    MagicOnionGeneratedClientInitializer.Resolver,
    //    // Add other standard resolvers (the list might vary based on your needs)
    //    StandardResolver.Instance
    //    // ... other resolvers
    //);

    //        MessagePackSerializer.DefaultOptions = MessagePackSerializer.DefaultOptions
    //            .WithResolver(StaticCompositeResolver.Instance);
        }
    }
}
