<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <TargetFrameworks>net11.0;net11.0-browser;net11.0-ios;net11.0-android;net11.0-macos</TargetFrameworks>
    <TargetFrameworks>$(TargetFrameworks);net11.0-windows</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsWindowsTarget>$([MSBuild]::IsOSPlatform('Windows'))</IsWindowsTarget>    
    <IsAndroidTarget>$([System.String]::Copy('$(TargetFramework)').Contains('-android'))</IsAndroidTarget>
    <IsIosTarget>$([System.String]::Copy('$(TargetFramework)').Contains('-ios'))</IsIosTarget>
    <IsMacTarget>$([System.String]::Copy('$(TargetFramework)').Contains('-macos'))</IsMacTarget>
    <IsBrowserTarget>$([System.String]::Copy('$(TargetFramework)').Contains('-browser'))</IsBrowserTarget>    
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <SupportedOSPlatformVersion Condition="'$(IsAndroidTarget)' == 'true'">24</SupportedOSPlatformVersion>
  </PropertyGroup>  

  <!-- Conditionally define the symbols -->
  <PropertyGroup>
    <DefineConstants Condition="'$(IsWindowsTarget)' == 'true'">$(DefineConstants);WINDOWS_OS</DefineConstants>
  </PropertyGroup>

  <!-- Start clean -->
  <ItemGroup>
    <Compile Remove="**\*.browser.cs" />
    <Compile Remove="**\*.windows.cs" />
    <Compile Remove="**\*.desktop.cs" />
  </ItemGroup>

  <!-- Windows -->
  <ItemGroup Condition="'$(IsWindowsTarget)' == 'true' AND '$(IsBrowserTarget)' != 'true' AND '$(IsMacTarget)' != 'true' AND '$(IsIosTarget)' != 'true'">
    <PackageReference Include="WindowsContracts.Net.Foundation.UniversalApiContract" Version="5.19041.10" />
    <Compile Include="**\*.windows.cs" />
    <Compile Include="**\*.desktop.cs" />
  </ItemGroup>

  <!-- Browser -->
  <ItemGroup Condition="'$(IsBrowserTarget)' == 'true'">
    <Compile Include="**\*.browser.cs" />
    <PackageReference Include="Avalonia.Browser" Version="12.1.1" />
  </ItemGroup>

  <!-- macOS -->
  <ItemGroup Condition="'$(IsMacTarget)' == 'true'">    
    <PackageReference Include="Microsoft.Maui.Platforms.MacOS.Essentials" Version="0.1.0-preview.12.26368.2" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />    
    <PackageReference Include="Avalonia.Controls.Maui.Essentials" Version="11.0.0-preview.6.26198.1455" />
    <PackageReference Include="Microsoft.Maui.Essentials" Version="11.0.0-preview.6.26360.8" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="11.0.0-preview.6.26359.118" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Avae.Shared\Avae.Shared.csproj" />
  </ItemGroup>
  
</Project>