<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net11.0;net11.0-windows;net11.0-android;net11.0-macos</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!-- Target-based detection (preferred) -->
    <!--<IsWindowsTarget>$(TargetFramework.Contains('-windows'))</IsWindowsTarget>-->

    <IsWindowsTarget>$([MSBuild]::IsOSPlatform('Windows'))</IsWindowsTarget>
    <IsWindowsTarget Condition="'$(IsWindowsTarget)' == 'false'">$(TargetFramework.Contains('-windows'))'</IsWindowsTarget>

    <IsAndroidTarget>$(TargetFramework.Contains('-android'))</IsAndroidTarget>
    <IsMacTarget>$([System.String]::Copy('$(TargetFramework)').Contains('-macos'))</IsMacTarget>
    <!--<IsWebProject Condition="'$(IsWebProject)' == ''">false</IsWebProject>-->
    <!-- Accept the value passed from the consumer -->
    <!--<IsWebProject>$(DefineConstants)</IsWebProject>    -->
    <!-- Detect both Microsoft.NET.Sdk.Web and Microsoft.NET.Sdk.BlazorWebAssembly -->
    <!--<IsWebProject>$(UsingMicrosoftNETSdkBlazorWebAssembly)</IsWebProject>-->
    <!--<IsWebProject Condition="'$(UsingMicrosoftNETSdkWeb)' == 'true' OR '$(UsingMicrosoftNETSdkBlazorWebAssembly)' == 'true' OR '$(UsingMicrosoftNETSdkWebAssembly)' == 'true'">true</IsWebProject>-->
    <!--<IsWebProject Condition="'$(MSBuildProjectExtension)' == '.csproj' AND '$(UsingMicrosoftNETSdk)' == 'true'">
      <IsWebProject Condition="'$(ProjectSdk)' == 'Microsoft.NET.Sdk.BlazorWebAssembly'">true</IsWebProject>
    </IsWebProject>-->
    <!--<IsWebProject>false</IsWebProject>-->
    <!-- Check if it's a Blazor WebAssembly project -->
    <!--<IsWebProject Condition="'$(ProjectSdk)' == 'Microsoft.NET.Sdk.BlazorWebAssembly' OR '$(ProjectSdk)' == 'Microsoft.NET.Sdk.Web'">true</IsWebProject>  -->
    
</PropertyGroup>
  <PropertyGroup>
    <SupportedOSPlatformVersion Condition="'$(IsAndroidTarget)' == 'true'">24</SupportedOSPlatformVersion>
  </PropertyGroup>

  <!-- Conditionally define the symbols -->
  <PropertyGroup>
    <DefineConstants>$(DefineConstants)</DefineConstants>
    <DefineConstants Condition="'$(IsWindowsTarget)' == 'true'">$(DefineConstants);IsWindowsOS</DefineConstants>
    <DefineConstants Condition="'$(IsWebProject)' == 'true'">$(DefineConstants);IsWebProject</DefineConstants>
    <!--<DefineConstants Condition="'$(IsAndroidTarget)' == 'true'">$(DefineConstants);ANDROID</DefineConstants>
    <DefineConstants Condition="'$(IsMacTarget)' == 'true'">$(DefineConstants);MACOS</DefineConstants>-->
  </PropertyGroup>

  

  <PropertyGroup Condition="'$(IsWebProject)' == 'true'">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <!-- Start clean -->
  <ItemGroup>
    <Compile Remove="**\*.browser.cs" />
    <Compile Remove="**\*.windows.cs" />
    <Compile Remove="**\*.desktop.cs" />
  </ItemGroup>

  <!-- Windows desktop (Avalonia etc.) -->
  <ItemGroup Condition="'$(IsWindowsTarget)' == 'true' AND '$(IsWebProject)' != 'true' AND '$(IsMacTarget)' != 'true'">
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="WindowsContracts.Net.Foundation.UniversalApiContract" Version="5.19041.10" />
    <Compile Include="**\*.windows.cs" />
    <Compile Include="**\*.desktop.cs" />
  </ItemGroup>

  <!-- Browser / Web -->
  <ItemGroup Condition="'$(IsWebProject)' == 'true'">
    <Compile Include="**\*.browser.cs" />
  </ItemGroup>

  <!-- macOS -->
  <ItemGroup Condition="'$(IsMacTarget)' == 'true'">
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Microsoft.Maui.Platforms.MacOS.Essentials" Version="0.1.0-preview.12.26368.2" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Controls.Maui.Essentials" Version="11.0.0-preview.6.26198.1455" />
    <PackageReference Include="Microsoft.Maui.Essentials" Version="11.0.0-preview.6.26360.8" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="11.0.0-preview.6.26359.118" />
  </ItemGroup>

</Project>