<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Update="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="MudBlazor" />
  </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Avae.Services\Avae.Services.csproj" />
      <ProjectReference Include="..\Avae.ViewModels\Avae.ViewModels.csproj" />
    </ItemGroup>
  
</Project>
