<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0-macos</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Native" />
    <PackageReference Include="Avalonia.HarfBuzz" />
    <PackageReference Include="Avalonia.Skia" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Example\Example.csproj" />
  </ItemGroup>

</Project>
